# Generated by Django 5.0 on 2023-12-26 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superuser',
            name='admin_ptr',
        ),
        migrations.AlterModelManagers(
            name='course',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_admin_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Идентификатор для админки'),
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='SuperUser',
        ),
    ]
